export const zonasSismicas = [
  {
    Seleccionar: [],
  },
  {
    Huanuco: [
      {
        Huanuco: [
          { Huanuco: 2 },
          { Amarilis: 2 },
          { "Pillco Marca": 2 },
          { Chinchao: 2 },
          { Churubamba: 2 },
          { Margos: 2 },
          { Quisqui: 2 },
          { "San Francisco de Cayran": 2 },
          { "San Pedro de Chaulan": 2 },
          { "Santa Maria del Valle": 2 },
          { Yarumayo: 2 },
        ],
      },
      {
        Huacaybamba: [{ Huacaybamba: 2 }, { Canchabamba: 2 }, { Cochabamba: 2 }, { Pinra: 2 }],
      },
      {
        "Leoncio Prado": [
          { "Rupa Rupa": 2 },
          { "Daniel Alomia Robles": 2 },
          { "Hermilio Valdizan": 2 },
          { "Jose Crespo y Castillo": 2 },
          { Luyando: 2 },
          { "Mariano Damaso Beraun": 2 },
        ],
      },
      {
        Marañon: [{ Huacrachuco: 2 }, { Cholon: 2 }, { "San Buenaventura": 2 }],
      },
      {
        "Puerto Inca": [
          { "Puerto Inca": 2 },
          { "Codo del Pozuzo": 2 },
          { Honoria: 2 },
          { Tournavista: 2 },
          { Yuyapichis: 2 },
        ],
      },
      {
        Yarowilca: [
          { Chavinillo: 2 },
          { Cahuac: 2 },
          { Chacabamba: 2 },
          { "Aparicio Pomares": 2 },
          { "Jacas Chico": 2 },
          { Obas: 2 },
          { Pampamarca: 2 },
          { Choras: 2 },
        ],
      },
      {
        Pachitea: [{ Panao: 2 }, { Chaglla: 2 }, { Molino: 2 }, { Umari: 2 }],
      },
      {
        Ambo: [
          { Ambo: 2 },
          { Cayna: 2 },
          { Colpas: 2 },
          { Conchamarca: 2 },
          { Huacar: 2 },
          { "San Francisco": 2 },
          { "San Rafael": 2 },
          { "Tomay Kichwa": 2 },
        ],
      },
      {
        Huamalies: [
          { Arancay: 2 },
          { "Chavin de Pariarca": 2 },
          { "Jacas Grande": 2 },
          { Jircan: 2 },
          { Monzon: 2 },
          { Punchao: 2 },
          { Singa: 2 },
          { Tantamayo: 2 },
          { Llata: 2 },
          { Miraflores: 2 },
          { Puños: 2 },
        ],
      },
      {
        "Dos de Mayo": [
          { "La Union": 3 },
          { Pachas: 3 },
          { Ripan: 3 },
          { Shunqui: 3 },
          { Sillapata: 3 },
          { Yanas: 3 },
          { Quivilla: 2 },
          { Marias: 2 },
          { Chuquis: 2 },
        ],
      },
      {
        Lauricocha: [
          { Jesus: 3 },
          { Baños: 3 },
          { Jivia: 3 },
          { Queropalca: 3 },
          { Rondos: 3 },
          { "San Francisco de Asis": 3 },
        ],
      },
    ],
    // Otras provincias con sus distritos y zonas sísmicas correspondientes
  },
  {
    Ancash: [
      {
        Huaraz: [
          { Huaraz: 2 },
          { Cochabamba: 2 },
          { Colcabamba: 2 },
          { Crespo: 2 },
          { Independencia: 2 },
          { Jangas: 2 },
          { Tarica: 2 },
          { Olleros: 2 },
          { Pampas: 2 },
          { Pariacoto: 2 },
          { Pira: 2 },
          { Willcahuain: 2 },
        ],
      },
      {
        Aija: [
          { Aija: 2 },
          { Coris: 2 },
          { Huacllan: 2 },
          { Huancaspama: 2 },
          { "La Merced": 2 },
          { Aijita: 2 },
          { Cachicadan: 2 },
          { Chiquian: 2 },
          { Chocas: 2 },
        ],
      },
      {
        Antonio_Raymondi: [
          { Llamellin: 2 },
          { Aczo: 2 },
          { Chaccho: 2 },
          { Chingas: 2 },
          { Mirgas: 2 },
          { "San Juan de Rontoy": 2 },
        ],
      },
      {
        Asuncion: [{ Chacas: 2 }, { Acochaca: 2 }],
      },
      {
        Bolognesi: [
          { Chiquian: 2 },
          { " Abelardo Pardo Lezameta": 2 },
          { " Antonio Raymondi": 2 },
          { Aquia: 2 },
          { Cajacay: 2 },
          { Colquioc: 2 },
          { Huallanca: 2 },
          { Huasta: 2 },
          { "La Primavera": 2 },
          { Mangas: 2 },
          { Pacllon: 2 },
          { "San Miguel de Corpanqui": 2 },
          { Ticllos: 2 },
        ],
      },
      // Agrega aquí las demás provincias y distritos de Ancash
    ],
  },
  // Otros departamentos con sus provincias, distritos y zonas sísmicas correspondientes
  // {
  //   Lima: [
  //     {
  //       Jesas: [
  //         { Huanuco: 3 },
  //         { Amarilis: 3 },
  //         { "Pillco Marca": 3 },
  //         { Chinchao: 3 },
  //         { Churubamba: 3 },
  //         { Margos: 3 },
  //         { Quisqui: 3 },
  //         { "San Francisco de Cayran": 3 },
  //         { "San Pedro de Chaulan": 3 },
  //         { "Santa María del Valle": 3 },
  //         { Yarumayo: 3 },
  //         { Panao: 3 },
  //         { Chaglla: 3 },
  //         { Molino: 3 },
  //         { Umari: 2 },
  //       ],
  //     },
  //     {
  //       Lima: [
  //         { "Tingo María": 2 },
  //         { "Mariano Dámaso Beraún": 2 },
  //         { "Daniel Alomía Robles": 2 },
  //         { "Hermilio Valdizan": 2 },
  //         { "José Crespo y Castillo": 2 },
  //         { Luyando: 2 },
  //         { "Miguel Grau": 2 },
  //         { "Rupa-Rupa": 2 },
  //         { "San Pablo de Pillao": 2 },
  //         { "Santa Rosa de Alto Yanajanca": 2 },
  //       ],
  //     },
  //     /*       'Dos de Mayo': {
  //       Chuquis: 2,
  //       'La Unión': 2,
  //       Marías: 2,
  //       Pachas: 2,
  //       Quivilla: 2,
  //       Ripan: 2,
  //       Shunqui: 2,
  //       Sillapata: 2,
  //       Yanas: 2,
  //     },
  //     Huacaybamba: {
  //       Huacaybamba: 2,
  //       Canchabamba: 2,
  //       Cochabamba: 2,
  //       Pinra: 2,
  //       Llata: 2,
  //       Miraflores: 2,
  //     },
  //     'Puerto Inca': {
  //       'Codo del Pozuzo': 2,
  //       Honoria: 2,
  //       'Puerto Inca': 2,
  //       Tournavista: 2,
  //       Yuyapichis: 2,
  //     },
  //     Huamalíes: {
  //       Llata: 3,
  //       Arancay: 2,
  //       'Chavín de Pariarca': 2,
  //       'Jacas Grande': 2,
  //       Jircan: 2,
  //       Miraflores: 3,
  //       Monzón: 2,
  //       Punchao: 2,
  //       Puños: 3,
  //       Singa: 2,
  //       Tantamayo: 2,
  //     }, */
  //     // Otras provincias con sus distritos y zonas sísmicas correspondientes
  //   ],
  //   // Otros departamentos con sus provincias, distritos y zonas sísmicas correspondientes
  // },
  {
    Lima: [
      {
        Cajatambo: [{ Cajatambo: 3 }, { Copa: 3 }, { Gorgor: 3 }, { Huancapon: 3 }, { Manas: 3 }],
      },
      {
        Oyon: [{ Oyon: 3 }, { Andajes: 3 }, { Caujul: 3 }, { Cochamarca: 3 }, { Navan: 3 }, { Pachangara: 3 }],
      },
      {
        Yauyos: [
          { Yauyos: 3 },
          { Alis: 3 },
          { Ayauca: 3 },
          { Ayaviri: 3 },
          { Azangaro: 3 },
          { Cacra: 3 },
          { Carania: 3 },
          { Catahuasi: 3 },
          { Chocos: 3 },
          { Cochas: 3 },
          { Colonia: 3 },
          { Hongos: 3 },
          { Huampara: 3 },
          { Huancaya: 3 },
          { Huangascar: 3 },
          { Huantan: 3 },
          { Huañec: 3 },
          { Laraos: 3 },
          { Lincha: 3 },
          { Madean: 3 },
          { Miraflores: 3 },
          { Putinza: 3 },
          { Quinches: 3 },
          { "San Joaquin": 3 },
          { "San Pedro de Pilas": 3 },
          { Tanta: 3 },
          { Tomas: 3 },
          { Tupe: 3 },
          { Viñac: 3 },
          { Vitis: 3 },
          { Omas: 4 },
          { Quinocay: 4 },
          { Tauripampa: 4 },
        ],
      },
      {
        Huarochiri: [
          { Matucana: 3 },
          { Callahuanca: 3 },
          { Carampoma: 3 },
          { Chicla: 3 },
          { Huachupampa: 3 },
          { Huanza: 3 },
          { Huarochiri: 3 },
          { Lahuaytambo: 3 },
          { Langa: 3 },
          { Laraos: 3 },
          { "San Andres de Tupicocha": 3 },
          { "San Bartolome": 3 },
          { "San Damian": 3 },
          { "San Juan de Iris": 3 },
          { "San Juan de Tantaranche": 3 },
          { "San Lorenzo de Quinti": 3 },
          { "San Mateo": 3 },
          { "San Mateo de Otao": 3 },
          { "San Pedro de Casta": 3 },
          { "San Pedro de Huancayre": 3 },
          { Sangallaya: 3 },
          { "Santa Cruz de Cocachacra": 3 },
          { "Santiago de Anchucaya": 3 },
          { "Santiago de Tuna": 3 },
          { Surco: 3 },
          { Antioquia: 4 },
          { Cuenca: 4 },
          { Mariatana: 4 },
          { "Ricardo Palma": 4 },
          { "San Antonio de Chaclla": 4 },
          { "Santa Eulalia": 4 },
          { "Santo Domingo de los Olleros": 4 },
        ],
      },
      {
        Canta: [
          { Canta: 3 },
          { Huaros: 3 },
          { Lachaqui: 3 },
          { "San Buenaventura": 3 },
          { Arahuay: 4 },
          { Huamantanga: 4 },
          { "Santa Rosa de Quives": 4 },
        ],
      },
      {
        Huaral: [
          { Huaral: 4 },
          { Aucallama: 4 },
          { Chancay: 4 },
          { "Atavillos Alto": 3 },
          { "Atavillos Bajo": 3 },
          { Ihuari: 3 },
          { Lampian: 3 },
          { Pacaraos: 3 },
          { "San Miguel de Acos": 3 },
          { "Santa Cruz de Andamarca": 3 },
          { Sumbilca: 3 },
          { "Veintisiete de Noviembre": 3 },
        ],
      },
      {
        Huaura: [
          { Checras: 3 },
          { "Leoncio Prado": 3 },
          { Paccho: 3 },
          { "Santa Leonor": 3 },
          { Huacho: 4 },
          { Ambar: 4 },
          { "Caleta de Carquin": 4 },
          { Hualmay: 4 },
          { Huaura: 4 },
          { "Santa Maria": 4 },
          { Sayán: 4 },
          { Vegueta: 4 },
        ],
      },
      {
        Cañete: [
          { "San Vicente de Cañete": 4 },
          { Asia: 4 },
          { Calango: 4 },
          { "Cerro Azul": 4 },
          { Chilca: 4 },
          { Coayllo: 4 },
          { Imperial: 4 },
          { Lunahuana: 4 },
          { Mala: 4 },
          { "Nuevo Imperial": 4 },
          { Pacaran: 4 },
          { Quilmana: 4 },
          { "San Antonio": 4 },
          { "San Luis": 4 },
          { "Santa Cruz de Flores": 4 },
          { Zuñiga: 3 },
        ],
      },
      {
        Barranca: [{ Barranca: 4 }, { Paramonga: 4 }, { Pativilca: 4 }, { Supe: 4 }, { "Supe Puerto": 4 }],
      },
      {
        Lima: [
          { Lima: 4 },
          { Ancon: 4 },
          { Ate: 4 },
          { Barranco: 4 },
          { Breña: 4 },
          { Carabayllo: 4 },
          { Chaclacayo: 4 },
          { Chorrillos: 4 },
          { Cieneguilla: 4 },
          { Comas: 4 },
          { "El Agustino": 4 },
          { Independencia: 4 },
          { "Jesus Maria": 4 },
          { "La Molina": 4 },
          { "La Victoria": 4 },
          { Lince: 4 },
          { "Los Olivos": 4 },
          { Lurigancho: 4 },
          { Lurin: 4 },
          { "Magdalena del Mar": 4 },
          { Miraflores: 4 },
          { Pachacamac: 4 },
          { Pucusana: 4 },
          { "Pueblo Libre": 4 },
          { "Puente Piedra": 4 },
          { "Punta Hermosa": 4 },
          { "Punta Negra": 4 },
          { Rimac: 4 },
          { "San Bartolo": 4 },
          { "San Borja": 4 },
          { "San Isidro": 4 },
          { "San Juan de Lurigancho": 4 },
          { "San Juan de Miraflores": 4 },
          { "San Luis": 4 },
          { "San Martin de Porres": 4 },
          { "San Miguel": 4 },
          { "Santa Anita": 4 },
          { "Santa Maria del Mar": 4 },
          { "Santa Rosa": 4 },
          { "Santiago de Surco": 4 },
          { Surquillo: 4 },
          { "Villa El Salvador": 4 },
          { "Villa Maria del Triunfo": 4 },
        ],
      },
    ],
  },
  {
    Amazonas: [
      {
        Chachapoyas: [
          { Asuncion: 2 },
          { Balsas: 2 },
          { Chachapoyas: 2 },
          { Cheto: 2 },
          { Chiliquin: 2 },
          { Chuquibamba: 2 },
          { Granada: 2 },
          { Huancas: 2 },
          { "La Jalca": 2 },
          { Levanto: 2 },
          { Leymebamba: 2 },
          { Magdalena: 2 },
          { "Mariscal Castilla": 2 },
          { Molinopampa: 2 },
          { Montevideo: 2 },
          { Olleros: 2 },
          { Quinjalca: 2 },
          { "San Francisco de Daguas": 2 },
          { "San Isidro de Maino": 2 },
          { Soloco: 2 },
          { Sonche: 2 },
        ],
      },
      {
        Bagua: [{ Aramango: 2 }, { Bagua: 2 }, { Copallin: 2 }, { "El Parco": 2 }, { Imaza: 2 }, { "La Peca": 2 }],
      },
      {
        Bongara: [
          { Chisquilla: 2 },
          { Churuja: 2 },
          { Corosha: 2 },
          { Cuispes: 2 },
          { Florida: 2 },
          { Jazan: 2 },
          { Jumbilla: 2 },
          { Recta: 2 },
          { "San Carlos": 2 },
          { Shipasbamba: 2 },
          { Valera: 2 },
          { Yambrasbamba: 2 },
        ],
      },
      {
        Condorcanqui: [{ "El Cenepa": 2 }, { Nieva: 2 }, { "Rio Santiago": 2 }],
      },
      {
        Luya: [
          { Camporredondo: 2 },
          { Cocabamba: 2 },
          { Colcamar: 2 },
          { Conila: 2 },
          { Inguilpata: 2 },
          { Lamud: 2 },
          { Longuita: 2 },
          { "Lonya Chico": 2 },
          { Luya: 2 },
          { "Luya Viejo": 2 },
          { Maria: 2 },
          { Ocalli: 2 },
          { Ocumal: 2 },
          { Pisuquia: 2 },
          { Providencia: 2 },
          { "San Cristobal": 2 },
          { "San Francisco del Yeso": 2 },
          { "San Jeronimo": 2 },
          { "San Juan de Lopecancha": 2 },
          { "Santa Catalina": 2 },
          { "Santo Tomas": 2 },
          { Tingo: 2 },
          { Trita: 2 },
        ],
      },
      {
        Utcubamba: [
          { "Bagua Grande": 2 },
          { Cajaruro: 2 },
          { Cumba: 2 },
          { "El Milagro": 2 },
          { Jamalca: 2 },
          { "Lonya Grande": 2 },
          { Yamon: 2 },
        ],
      },
      {
        "Rodriguez de Mendoza": [
          { Chirimoto: 2 },
          { Cochamal: 2 },
          { Huambo: 2 },
          { Limabamba: 2 },
          { Longar: 2 },
          { "Mariscal Benavides": 2 },
          { Milpuc: 2 },
          { Omia: 2 },
          { "San Nicolas": 2 },
          { "Santa Rosa": 2 },
          { Totora: 2 },
          { "Vista Alegre": 3 },
        ],
      },
    ],
  },
  {
    Ancash: [
      {
        "Antonio Raymondi": [
          { Chaccho: 2 },
          { Chingas: 2 },
          { Llamesin: 2 },
          { Aczo: 3 },
          { Mirgas: 3 },
          { "San Juan de Rontoy": 3 },
        ],
      },
      {
        Huari: [
          { Anra: 2 },
          { Huacachi: 2 },
          { Huacchis: 2 },
          { Paucas: 2 },
          { Rapayan: 2 },
          { Uco: 2 },
          { Huari: 3 },
          { Cajay: 3 },
          { "Chavin de Huantar": 3 },
          { Huachis: 3 },
          { Huantar: 3 },
          { Masin: 3 },
          { Ponto: 3 },
          { Rahuapampa: 3 },
          { "San Marcos": 3 },
          { "San Pedro de Chana": 3 },
        ],
      },
      {
        Asuncion: [{ Chacas: 3 }, { Acochaca: 3 }],
      },
      {
        Carhuaz: [
          { Carhuaz: 3 },
          { Acopampa: 3 },
          { Amashca: 3 },
          { Anta: 3 },
          { Ataquero: 3 },
          { Marcara: 3 },
          { Pariahuanca: 3 },
          { "San Miguel de Aco": 3 },
          { Shilla: 3 },
          { Tinco: 3 },
          { Yungar: 3 },
        ],
      },
      {
        "Carlos F. Fitzcarrald": [{ "San Luis": 3 }, { "San Nicolas": 3 }, { Yauya: 3 }],
      },
      {
        Corongo: [
          { Aco: 3 },
          { Bambas: 3 },
          { Corongo: 3 },
          { Cusca: 3 },
          { "La Pampa": 3 },
          { Yanac: 3 },
          { Yupan: 3 },
        ],
      },
      {
        "Mariscal Luzuriaga": [
          { Casca: 3 },
          { "Eleazar Guzman Barron": 3 },
          { "Fidel Olivas Escudero": 3 },
          { Llama: 3 },
          { Llumpa: 3 },
          { Lucma: 3 },
          { Musga: 3 },
          { Piscobamba: 3 },
        ],
      },
      {
        Pallasca: [
          { Bolognesi: 3 },
          { Cabana: 3 },
          { Conchucos: 3 },
          { Huacaschuque: 3 },
          { Huandoval: 3 },
          { Lacabamba: 3 },
          { Llapo: 3 },
          { Pallasca: 3 },
          { Pampas: 3 },
          { "Santa Rosa": 3 },
          { Tauca: 3 },
        ],
      },
      {
        Pomabamba: [{ Huayllan: 3 }, { Parobamba: 3 }, { Pomabamba: 3 }, { Quinuabamba: 3 }],
      },
      {
        Sihuas: [
          { Acobamba: 3 },
          { "Alfonso Ugarte": 3 },
          { Cashapampa: 3 },
          { Chingalpo: 3 },
          { Huayllabamba: 3 },
          { Quiches: 3 },
          { Ragash: 3 },
          { "San Juan": 3 },
          { Sicsibamba: 3 },
          { Sihuas: 3 },
        ],
      },
      {
        Huaylas: [
          { Caraz: 3 },
          { Huallanca: 3 },
          { Huata: 3 },
          { Huaylas: 3 },
          { Mato: 3 },
          { Pamparomas: 3 },
          { "Pueblo Libre": 3 },
          { "Santa Cruz": 3 },
          { "Santo Toribio": 3 },
          { Yuracmarca: 3 },
        ],
      },
      {
        Yungay: [
          { Yungay: 3 },
          { Cascapara: 3 },
          { Mancos: 3 },
          { Matacoto: 3 },
          { Quillo: 3 },
          { Ranrahirca: 3 },
          { Shupluy: 3 },
          { Yanama: 3 },
        ],
      },
      {
        Huaraz: [
          { Huaraz: 3 },
          { Cochabamba: 3 },
          { Colcabamba: 3 },
          { Huanchay: 3 },
          { Independencia: 3 },
          { Jangas: 3 },
          { "La Libertad": 3 },
          { Olleros: 3 },
          { Pampas: 3 },
          { Pariacoto: 3 },
          { Pira: 3 },
          { Tarica: 3 },
        ],
      },
      {
        Bolognesi: [
          { Chiquian: 3 },
          { "Abelardo Pardo Lezameta": 3 },
          { "Antonio Raymondi": 3 },
          { Aquia: 3 },
          { Cajacay: 3 },
          { Canis: 3 },
          { Colquioc: 3 },
          { Huallanca: 3 },
          { Huasta: 3 },
          { Huayllacayan: 3 },
          { "La Primavera": 3 },
          { Mangas: 3 },
          { Pacllon: 3 },
          { "San Miguel de Corpanqui": 3 },
          { Ticllos: 3 },
        ],
      },
      {
        Recuay: [
          { Recuay: 3 },
          { Catac: 3 },
          { Cotaparaco: 3 },
          { Huayllapampa: 3 },
          { Llacllin: 3 },
          { Marca: 3 },
          { "Pampas Chico": 3 },
          { Pararin: 3 },
          { Tapacocha: 3 },
          { Ticapampa: 3 },
        ],
      },
      {
        Aija: [{ Aija: 3 }, { Coris: 3 }, { Huacllan: 4 }, { "La Merced": 4 }, { Succha: 4 }],
      },
      {
        Ocros: [
          { Ocros: 3 },
          { Acas: 3 },
          { Cajamarquilla: 3 },
          { Carhuapampa: 3 },
          { Congas: 3 },
          { Llipa: 3 },
          { "San Cristobal de Rajan": 3 },
          { "Santiago de Chilcas": 3 },
          { Cochas: 4 },
          { "San Pedro": 4 },
        ],
      },
      {
        Huarmey: [{ Huarmey: 4 }, { Culebras: 4 }, { Cochapeti: 3 }, { Huayan: 3 }, { Malvas: 3 }],
      },
      {
        Santa: [
          { "Caceres del Peru": 3 },
          { Macate: 3 },
          { Moro: 3 },
          { Chimbote: 4 },
          { Coishco: 4 },
          { Nepeña: 4 },
          { Samanco: 4 },
          { Santa: 4 },
          { "Nuevo Chimbote": 4 },
        ],
      },
      {
        Casma: [{ Casma: 4 }, { "Buena Vista Alta": 4 }, { "Comandante Noel": 4 }, { Yautan: 4 }],
      },
    ],
  },
  {
    Apurimac: [
      {
        Cotabambas: [
          { Callhuahuacho: 2 },
          { Cotabambas: 2 },
          { Coyllurqui: 2 },
          { Haquira: 2 },
          { Mara: 2 },
          { Tambobamba: 2 },
        ],
      },
      {
        Grau: [
          { Chuquibambilla: 2 },
          { Curasco: 2 },
          { Curpahuasi: 2 },
          { Gamarra: 2 },
          { Huayllati: 2 },
          { Mamara: 2 },
          { "Micaela Bastidas": 2 },
          { Pataypampa: 2 },
          { Progreso: 2 },
          { "San Antonio": 2 },
          { "Santa Rosa": 2 },
          { Turpay: 2 },
          { Vilcabamba: 2 },
          { Virundo: 2 },
        ],
      },
      {
        Abancay: [
          { Abancay: 2 },
          { Chacoche: 2 },
          { Circa: 2 },
          { Curahuasi: 2 },
          { Huanipaca: 2 },
          { Lambrama: 2 },
          { Pichirhua: 2 },
          { "San Pedro de Cachora": 2 },
          { Tamburco: 2 },
        ],
      },
      {
        Chincheros: [
          { "Anco-Huallo": 2 },
          { Chincheros: 2 },
          { Cocharcas: 2 },
          { Huaccana: 2 },
          { Ocobamba: 2 },
          { Ongoy: 2 },
          { Ranracancha: 2 },
          { Uranmarca: 2 },
          { "El Porvenir": 2 },
          { "Los Chankas": 2 },
          { Rochacc: 2 },
        ],
      },
      {
        Andahuaylas: [
          { Andahuaylas: 2 },
          { Andarapa: 2 },
          { Huancarama: 2 },
          { Huancaray: 2 },
          { Kaquiabamba: 2 },
          { Kishuara: 2 },
          { Pacobamba: 2 },
          { Pacucha: 2 },
          { "San Antonio de Cachi": 2 },
          { "San Jeronimo": 2 },
          { "Santa Maria de Chicmo": 2 },
          { Talavera: 2 },
          { Turpo: 2 },
          { Chiara: 3 },
          { Huayana: 3 },
          { Pampachiri: 3 },
          { Pomacocha: 3 },
          { "San Miguel de Chaccrampa": 3 },
          { "Tumay Huaraca": 3 },
        ],
      },
      {
        Aymaraes: [
          { Chapimarca: 2 },
          { Colcabamba: 2 },
          { Lucre: 2 },
          { "San Juan de Chacña": 2 },
          { Tintay: 2 },
          { Capaya: 3 },
          { Caraybamba: 3 },
          { Chalhuanca: 3 },
          { Cotaruse: 3 },
          { Huayllo: 3 },
          { "Justo Apu Sahuaraura": 3 },
          { Pocohuanca: 3 },
          { Sañayca: 3 },
          { Soraya: 3 },
          { Tapairihua: 3 },
          { Toraya: 3 },
          { Yanaca: 3 },
        ],
      },
      {
        Antabamba: [
          { Antabamba: 3 },
          { "El Oro": 3 },
          { Huaquirca: 3 },
          { "Juan Espinoza Medrano": 3 },
          { Oropesa: 3 },
          { Pachaconas: 3 },
          { Sabaino: 3 },
        ],
      },
    ],
  },
  {
    Arequipa: [
      {
        "La Union": [
          { Cotahuasi: 3 },
          { Alca: 3 },
          { Charcana: 3 },
          { Huaynacotas: 3 },
          { Pampamarca: 3 },
          { Puyca: 3 },
          { Quechualla: 3 },
          { Sayla: 3 },
          { Tauria: 3 },
          { Tomepampa: 3 },
          { Toro: 3 },
        ],
      },
      {
        Caylloma: [
          { Chivay: 3 },
          { Achoma: 3 },
          { Cabanaconde: 3 },
          { Callalli: 3 },
          { Caylloma: 3 },
          { Coporaque: 3 },
          { Huambo: 3 },
          { Huanca: 3 },
          { Ichupampa: 3 },
          { Lari: 3 },
          { Lluta: 3 },
          { Maca: 3 },
          { Madrigal: 3 },
          { "San Antonio de Chuca": 3 },
          { Sibayo: 3 },
          { Tapay: 3 },
          { Tisco: 3 },
          { Tuti: 3 },
          { Yanque: 3 },
          { Majes: 4 },
        ],
      },
      {
        Castilla: [
          { Andagua: 3 },
          { Ayo: 3 },
          { Chachas: 3 },
          { Chilcaymarca: 3 },
          { Choco: 3 },
          { Machaguay: 3 },
          { Orcopampa: 3 },
          { Pampacolca: 3 },
          { Tipan: 3 },
          { Uñon: 3 },
          { Viraco: 3 },
          { Aplao: 4 },
          { Huancarqui: 4 },
          { Uraca: 4 },
        ],
      },
      {
        Arequipa: [
          { Arequipa: 3 },
          { "Alto Selva Alegre": 3 },
          { Cayma: 3 },
          { "Cerro Colorado": 3 },
          { Characato: 3 },
          { Chiguata: 3 },
          { "Jacobo Hunter": 3 },
          { "Jose Luis Bustamante y Rivero": 3 },
          { "Mariano Melgar": 3 },
          { Miraflores: 3 },
          { Mollelbaya: 3 },
          { Paucarpata: 3 },
          { Pocsi: 3 },
          { Quequeña: 3 },
          { Sabandia: 3 },
          { Sachaca: 3 },
          { "San Juan de Tarucani": 3 },
          { Socabaya: 3 },
          { Tiabaya: 3 },
          { Yanahuara: 3 },
          { Yura: 3 },
          { "La Joya": 4 },
          { Polobaya: 4 },
          { "San Juan de Siguas": 4 },
          { "Santa Isabel de Siguas": 4 },
          { "Santa Rita de Siguas": 4 },
          { Uchumayo: 4 },
          { Vitor: 4 },
          { Yarabamba: 4 },
        ],
      },
      {
        Condesuyos: [
          { Cayarani: 3 },
          { Chichas: 3 },
          { Salamanca: 3 },
          { Chuquibamba: 4 },
          { Andaray: 4 },
          { Iray: 4 },
          { "Rio Grande": 4 },
          { Yanaquihua: 4 },
        ],
      },
      {
        Islay: [
          { Mollendo: 4 },
          { Cocachacra: 4 },
          { "Dean Valdivia": 4 },
          { Islay: 4 },
          { Mejia: 4 },
          { "Punta de Bombon": 4 },
        ],
      },
      {
        Camana: [
          { Camana: 4 },
          { "Jose Maria Quimper": 4 },
          { "Mariano Nicolas Valcarcel": 4 },
          { "Mariscal Caceres": 4 },
          { "Nicolas de Pierola": 4 },
          { Ocoña: 4 },
          { Quilca: 4 },
          { "Samuel Pastor": 4 },
        ],
      },
      {
        Caraveli: [
          { Caraveli: 4 },
          { Acari: 4 },
          { Atico: 4 },
          { Atiquipa: 4 },
          { "Bella Union": 4 },
          { Cahuacho: 4 },
          { Chala: 4 },
          { Chaparri: 4 },
          { Huanuhuanu: 4 },
          { Jaqui: 4 },
          { Lomas: 4 },
          { Quicacha: 4 },
          { Yauca: 4 },
        ],
      },
    ],
  },
  {
    Ayacucho: [
      {
        Huanta: [
          { Ayahuanco: 2 },
          { Iguaín: 2 },
          { Huamanguilla: 2 },
          { Huanta: 2 },
          { Llochegua: 2 },
          { Luricocha: 2 },
          { Santillana: 2 },
          { Sivia: 2 },
          { Chaca: 2 },
        ],
      },
      {
        "La Mar": [
          { Anco: 2 },
          { Ayna: 2 },
          { Chilcas: 2 },
          { Chungui: 2 },
          { "Luis Carranza": 2 },
          { "San Miguel": 2 },
          { "Santa Rosa": 2 },
          { Tambo: 2 },
          { Oronccoy: 2 },
        ],
      },
      {
        Huamanga: [
          { Acocro: 2 },
          { Acosvinchos: 2 },
          { Ayacucho: 2 },
          { "Jesús Nazareno": 2 },
          { Ocros: 2 },
          { Pacaycasa: 2 },
          { Quinua: 2 },
          { "San José de Ticllas": 2 },
          { "Santiago de Pischa": 2 },
          { Tambillo: 2 },
          { "Carmen Alto": 3 },
          { Chiara: 3 },
          { "San Juan Bautista": 3 },
          { Socos: 3 },
          { Vinchos: 3 },
        ],
      },
      {
        Vilcashuaman: [
          { Concepción: 2 },
          { Accomarca: 3 },
          { Carhuanca: 3 },
          { Huambalpa: 3 },
          { Independencia: 3 },
          { Saurama: 3 },
          { Vilcashuaman: 3 },
          { Vischongo: 3 },
        ],
      },
      {
        "Huanca Sancos": [{ Carapo: 3 }, { Sacsamarca: 3 }, { Sancos: 3 }, { "Santiago de Lucanamarca": 3 }],
      },
      {
        Cangallo: [
          { Cangallo: 3 },
          { Chuschi: 3 },
          { "Los Morochucos": 3 },
          { "María Parado de Bellido": 3 },
          { Paras: 3 },
          { Totos: 3 },
        ],
      },
      {
        "Paucar del Sara Sara": [
          { Colta: 3 },
          { Corculla: 3 },
          { Lampa: 3 },
          { Marcabamba: 3 },
          { Oyolo: 3 },
          { Pararca: 3 },
          { Pausa: 3 },
          { "San Javier de Alpabamba": 3 },
          { "San José de Ushua": 3 },
          { "Sara Sara": 3 },
        ],
      },
      {
        Sucre: [
          { Belén: 3 },
          { Chalcos: 3 },
          { Chilcayoc: 3 },
          { Huacaña: 3 },
          { Morcolla: 3 },
          { Paico: 3 },
          { Querobamba: 3 },
          { "San Pedro de Larcay": 3 },
          { "San Salvador de Quije": 3 },
          { "Santiago de Paucaray": 3 },
          { Soras: 3 },
        ],
      },
      {
        "Víctor Fajardo": [
          { Alcamenca: 3 },
          { Aponfo: 3 },
          { Asquipata: 3 },
          { Canaria: 3 },
          { Cayara: 3 },
          { Colca: 3 },
          { Huamanquiquia: 3 },
          { Huancapi: 3 },
          { Huancaraylla: 3 },
          { Huaya: 3 },
          { Sarhua: 3 },
          { Vilcanchos: 3 },
        ],
      },
      {
        Parinacochas: [
          { Chumpi: 3 },
          { Coracora: 3 },
          { "Coronel Castañeda": 3 },
          { Pacapausa: 3 },
          { "San Francisco de Ravacayco": 3 },
          { Upahuacho: 3 },
          { Pullo: 4 },
          { Puyusca: 4 },
        ],
      },
      {
        Lucanas: [
          { Aucara: 3 },
          { Cabana: 3 },
          { "Carmen Salcedo": 3 },
          { Chaviña: 3 },
          { Chipao: 3 },
          { Lucanas: 3 },
          { Puquio: 3 },
          { "San Juan": 3 },
          { "San Pedro de Palco": 3 },
          { "Santa Ana de Huaycahuacho": 3 },
          { "Huac-Huas": 4 },
          { Laramate: 4 },
          { "Leoncio Prado": 4 },
          { Llauta: 4 },
          { Ocaña: 4 },
          { Otoca: 4 },
          { Saisa: 4 },
          { "San Cristóbal": 4 },
          { "San Pedro": 4 },
          { Sancos: 4 },
          { "Santa Lucía": 4 },
        ],
      },
    ],
  },
  {
    Cajamarca: [
      {
        Hualgayoc: [{ Bambamarca: 2 }, { Chugur: 2 }, { Hualgayoc: 2 }],
      },
      {
        "San Ignacio": [
          { "San Ignacio": 2 },
          { Chirinos: 2 },
          { Huarango: 2 },
          { "La Coipa": 2 },
          { Namballe: 2 },
          { "San Jose de Lourdes": 2 },
          { Tabaconas: 2 },
        ],
      },
      {
        Celendin: [
          { Celendin: 2 },
          { Chumuch: 2 },
          { Cortegana: 2 },
          { Huasmin: 2 },
          { "Jorge Chavez": 2 },
          { "Jose Galvez": 2 },
          { "Miguel Iglesias": 2 },
          { Oxamarca: 2 },
          { Sorochuco: 2 },
          { Sucre: 2 },
          { Utco: 2 },
          { "La Libertad de Pallan": 2 },
        ],
      },
      {
        Cutervo: [
          { Cutervo: 2 },
          { Callayuc: 2 },
          { Choros: 2 },
          { Cujillo: 2 },
          { "La Ramada": 2 },
          { Pimpingos: 2 },
          { "San Andres de Cutervo": 2 },
          { "San Juan de Cutervo": 2 },
          { "San Luis de Lucma": 2 },
          { "Santa Cruz": 2 },
          { "Santo Domingo de la Capilla": 2 },
          { "Santo Tomas": 2 },
          { Socota: 2 },
          { "Toribio Casanova": 2 },
          { Querocotillo: 3 },
        ],
      },
      {
        Jaen: [
          { Jaen: 2 },
          { Bellavista: 2 },
          { Chontali: 2 },
          { Colasay: 2 },
          { Huabal: 2 },
          { "Las Pirias": 2 },
          { "San Jose del Alto": 2 },
          { "Santa Rosa": 2 },
          { Pomahuaca: 3 },
          { Pucara: 3 },
          { Sallique: 3 },
          { "San Felipe": 3 },
        ],
      },
      {
        "San Marcos": [
          { "Gregorio Pita": 2 },
          { Ichocan: 2 },
          { "Jose Manuel Quiroz": 2 },
          { "Jose Sabogal": 2 },
          { Chancay: 3 },
          { "Eduardo Villanueva": 3 },
          { "Pedro Galvez": 3 },
        ],
      },
      {
        Chota: [
          { Chota: 2 },
          { Anguia: 2 },
          { Chadin: 2 },
          { Chiguirip: 2 },
          { Chimban: 2 },
          { Choropampa: 2 },
          { Conchan: 2 },
          { Lajas: 2 },
          { Paccha: 2 },
          { Pion: 2 },
          { Tacabamba: 2 },
          { Cochabamba: 3 },
          { Huambos: 3 },
          { Llama: 3 },
          { Miracosta: 3 },
          { Querocoto: 3 },
          { "San Juan de Licupis": 3 },
          { Tocmoche: 3 },
        ],
      },
      {
        Cajabamba: [{ Cajabamba: 3 }, { Cachachi: 3 }, { Condebamba: 3 }, { Sitacocha: 2 }],
      },
      {
        Cajamarca: [
          { Encañada: 2 },
          { Cajamarca: 3 },
          { Asuncion: 3 },
          { Chetilla: 3 },
          { Cospan: 3 },
          { Jesus: 3 },
          { Llacanora: 3 },
          { "Los Baños del Inca": 3 },
          { Magdalena: 3 },
          { Matara: 3 },
          { Namora: 3 },
        ],
      },
      {
        Contumaza: [
          { Contumaza: 3 },
          { Chilete: 3 },
          { Cupisnique: 3 },
          { Guzmango: 3 },
          { "San Benito": 3 },
          { "Santa Cruz de Toled": 3 },
          { Tantarica: 3 },
          { Yonan: 3 },
        ],
      },
      {
        "San Miguel": [
          { "San Miguel": 3 },
          { Bolivar: 3 },
          { Calquis: 3 },
          { Catilluc: 3 },
          { "El Prado": 3 },
          { "La Florida": 3 },
          { Llapa: 3 },
          { Nanchoc: 3 },
          { Niepos: 3 },
          { "San Gregorio": 3 },
          { "San Silvestre de Cochan": 3 },
          { Tongod: 3 },
          { "Union Agua Blanca": 3 },
        ],
      },
      {
        "San Pablo": [{ "San Pablo": 3 }, { "San Bernardino": 3 }, { "San Luis": 3 }, { Tumbaden: 3 }],
      },
      {
        "Santa Cruz": [
          { "Santa Cruz": 3 },
          { Andabamba: 3 },
          { Catache: 3 },
          { Chancaybaños: 3 },
          { "La Esperanza": 3 },
          { Ninabamba: 3 },
          { Pulan: 3 },
          { Saucepampa: 3 },
          { Sexi: 3 },
          { Uticyacu: 3 },
          { Yauyucan: 3 },
        ],
      },
    ],
  },
  {
    Callao: [
      {
        Callao: [
          { Callao: 4 },
          { Bellavista: 4 },
          { "Carmen de la Legua Reynoso": 4 },
          { "La Perla": 4 },
          { "La Punta": 4 },
          { Ventanilla: 4 },
          { "Mi Peru": 4 },
        ],
      },
    ],
  },
  {
    Cusco: [
      {
        Calca: [
          { Calca: 2 },
          { Coya: 2 },
          { Lamay: 2 },
          { Lares: 2 },
          { Pisac: 2 },
          { "San Salvador": 2 },
          { Taray: 2 },
          { Yanatile: 2 },
        ],
      },
      {
        Urubamba: [
          { Urubamba: 2 },
          { Chinchero: 2 },
          { Huayllabamba: 2 },
          { Machupicchu: 2 },
          { Maras: 2 },
          { Ollantaytambo: 2 },
          { Yucay: 2 },
        ],
      },
      {
        Paucartambo: [
          { Paucartambo: 2 },
          { Caicay: 2 },
          { Challabamba: 2 },
          { Colquepata: 2 },
          { Huancarani: 2 },
          { Kosñipata: 2 },
        ],
      },
      {
        Anta: [
          { Anta: 2 },
          { Ancahuasi: 2 },
          { Cachimayo: 2 },
          { Chinchaypujio: 2 },
          { Huarocondo: 2 },
          { Limatambo: 2 },
          { Mollepata: 2 },
          { Pucyura: 2 },
          { Zurite: 2 },
        ],
      },
      {
        Quispicanchis: [
          { Urcos: 2 },
          { Andahuaylillas: 2 },
          { Camanti: 2 },
          { Ccarhuayo: 2 },
          { Ccatca: 2 },
          { Cusipata: 2 },
          { Huaroc: 2 },
          { Lucre: 2 },
          { Marcapata: 2 },
          { Ocongate: 2 },
          { Oropesa: 2 },
        ],
      },
      {
        Paruro: [
          { Paruro: 2 },
          { Accha: 2 },
          { Ccapi: 2 },
          { Colcha: 2 },
          { Huanoquite: 2 },
          { Omacha: 2 },
          { Paccaritambo: 2 },
          { Pillpinto: 2 },
          { Yaurisque: 2 },
        ],
      },
      {
        Canchis: [
          { Sicuani: 2 },
          { Checacupe: 2 },
          { Combapata: 2 },
          { Marangani: 2 },
          { Pitumarca: 2 },
          { "San Pablo": 2 },
          { "San Pedro": 2 },
          { Tinta: 2 },
        ],
      },
      {
        Canas: [
          { Yanaoca: 2 },
          { Checca: 2 },
          { Kunturkanki: 2 },
          { Langui: 2 },
          { Layo: 2 },
          { Pampamarca: 2 },
          { Quehue: 2 },
          { "Tupac Amaru": 2 },
        ],
      },
      {
        Acomayo: [
          { Acomayo: 3 },
          { Acopia: 3 },
          { Acos: 3 },
          { "Mosoc Llacta": 4 },
          { Pomacanchi: 3 },
          { Rondocan: 3 },
          { Sangarara: 3 },
        ],
      },
      {
        Cusco: [
          { Cusco: 3 },
          { Ccorca: 3 },
          { Poroy: 3 },
          { "San Jeronimo": 3 },
          { "San Sebastian": 3 },
          { Santiago: 3 },
          { Saylla: 3 },
          { Wanchaq: 3 },
        ],
      },
      {
        "La Convencion": [
          { "Santa Ana": 2 },
          { Echarate: 2 },
          { Huayopata: 2 },
          { Maranura: 2 },
          { Ocobamba: 2 },
          { Quellouno: 2 },
          { Kimbiri: 2 },
          { Pichari: 2 },
          { "Villa Virgen": 2 },
          { "Villa Kintiarina": 2 },
          { Megantoni: 2 },
        ],
      },
      {
        Chumbivilcas: [
          { Capacmarca: 2 },
          { Chamaca: 2 },
          { Colquemarca: 2 },
          { Livitaca: 2 },
          { "Santo Tomas": 3 },
          { Llusco: 3 },
          { Quiñota: 3 },
          { Velille: 3 },
        ],
      },
      {
        Espinar: [
          { Espinar: 3 },
          { Condoroma: 3 },
          { Coporaque: 3 },
          { Ocoruro: 3 },
          { Pallpata: 3 },
          { Pichigua: 3 },
          { Suyckutambo: 3 },
          { "Alto Pichigua": 3 },
        ],
      },
    ],
  },
  {
    Huancavelica: [
      {
        Churcampa: [
          { Anco: 2 },
          { Chinchihuasi: 2 },
          { Churcampa: 2 },
          { Cosme: 2 },
          { "El Carmen": 2 },
          { "La Merced": 2 },
          { Locroja: 2 },
          { Pachamarca: 2 },
          { Paucarbamba: 2 },
          { "San Miguel de Mayocc": 2 },
          { "San Pedro de Coris": 2 },
        ],
      },
      {
        Acobamba: [
          { Acobamba: 2 },
          { Andabamba: 2 },
          { Anta: 2 },
          { Caja: 2 },
          { Marcas: 2 },
          { Paucara: 2 },
          { Pomacocha: 2 },
          { Rosario: 2 },
        ],
      },
      {
        Tayacaja: [
          { Colcabamba: 2 },
          { "Daniel Hernandez": 2 },
          { Huachocolpa: 2 },
          { Huaribamba: 2 },
          { Quishuar: 2 },
          { Salcabamba: 2 },
          { "San Marcos de Rocchac": 2 },
          { Salcahuasi: 2 },
          { Surcubamba: 2 },
          { "Tintay Puncu": 2 },
          { Pichos: 2 },
          { Roble: 2 },
          { Acostambo: 3 },
          { Acraquia: 3 },
          { Ahuaycha: 3 },
          { Huando: 3 },
          { Ñahuimpuquio: 3 },
          { Pampas: 3 },
          { Pazos: 3 },
          { "Santiago de Tucuma": 3 },
        ],
      },
      {
        Angaraes: [
          { Chincho: 2 },
          { Anchonga: 3 },
          { Callanmarca: 3 },
          { Ccochaccasa: 3 },
          { Congalla: 3 },
          { "Huanca Huanca": 3 },
          { "Huayllay Grande": 3 },
          { Julcamarca: 3 },
          { Lircay: 3 },
          { "San Antonio de Antaparco": 3 },
          { Secclla: 3 },
          { "Santo Tomas de Pata": 3 },
        ],
      },
      {
        Huancavelica: [
          { Acobambilla: 3 },
          { Acoria: 3 },
          { Ascension: 3 },
          { Conayca: 3 },
          { Cuenca: 3 },
          { Huachocolpa: 3 },
          { Huancavelica: 3 },
          { Huayllahuara: 3 },
          { Izcuchaca: 3 },
          { Laria: 3 },
          { Manta: 3 },
          { "Mariscal Caceres": 3 },
          { Moya: 3 },
          { "Nuevo Occoro": 3 },
          { Palca: 3 },
          { Pilchaca: 3 },
          { Vilca: 3 },
          { Yauli: 3 },
        ],
      },
      {
        Castrovirreyna: [
          { Arma: 3 },
          { Aurahua: 3 },
          { Castrovirreyna: 3 },
          { Chupamarca: 3 },
          { Cocas: 3 },
          { Huachos: 3 },
          { Huamatambo: 3 },
          { Mollepampa: 3 },
          { "Santa Ana": 3 },
          { Tantara: 3 },
          { Ticrapo: 3 },
          { Capillas: 4 },
          { "San Juan": 4 },
        ],
      },
      {
        Huaytara: [
          { "San Antonio de Cusicancha": 3 },
          { Pilpichaca: 3 },
          { Querco: 3 },
          { Ayavi: 4 },
          { Cordova: 4 },
          { "Huayacundo Arma": 4 },
          { Huaytara: 4 },
          { Laramarca: 4 },
          { Ocoyo: 4 },
          { "Quito Arma": 4 },
          { "San Francisco de Sangayaico": 4 },
          { "San Isidro": 4 },
          { "Santiago de Chocorvos": 4 },
          { "Santiago de Quirahuara": 4 },
          { "Santo Domingo de Capillas": 4 },
          { Tambo: 4 },
        ],
      },
    ],
  },
  {
    Ica: [
      {
        Chincha: [
          { "San Pedro de Huacarpana": 3 },
          { "Alto Laran": 4 },
          { Chavin: 4 },
          { "Chincha Alta": 4 },
          { "Chincha Baja": 4 },
          { "El Carmen": 4 },
          { "Grocio Prado": 4 },
          { "Pueblo Nuevo": 4 },
          { "San Juan de Yanac": 4 },
          { Sunampe: 4 },
          { "Tambo de Mora": 4 },
        ],
      },
      {
        Palpa: [{ Llipata: 4 }, { Palpa: 4 }, { "Rio Grande": 4 }, { "Santa Cruz": 4 }, { Tibillo: 4 }],
      },
      {
        Ica: [
          { Ica: 4 },
          { "La Tinguiña": 4 },
          { "Los Aquijes": 4 },
          { Ocucaje: 4 },
          { Pachacutec: 4 },
          { Parcona: 4 },
          { "Pueblo Nuevo": 4 },
          { Salas: 4 },
          { "San Jose de los Molinos": 4 },
          { "San Juan Bautista": 4 },
          { Santiago: 4 },
          { Subtanjalla: 4 },
          { Tate: 4 },
          { "Yauca del Rosario": 4 },
        ],
      },
      {
        Nazca: [{ Changuillo: 4 }, { "El Ingenio": 4 }, { Marcona: 4 }, { Nazca: 4 }, { "Vista Alegre": 4 }],
      },
      {
        Pisco: [
          { Huancano: 4 },
          { Humay: 4 },
          { Independencia: 4 },
          { Paracas: 4 },
          { Pisco: 4 },
          { "San Andres": 4 },
          { "San Clemente": 4 },
          { "Tupac Amaru Inca": 4 },
        ],
      },
    ],
  },
  {
    Junin: [
      {
        Chanchamayo: [
          { Chanchamayo: 2 },
          { Perene: 2 },
          { Pichanaqui: 2 },
          { "San Luis de Shuaro": 2 },
          { "San Ramon": 2 },
          { Vitoc: 2 },
        ],
      },
      {
        Satipo: [
          { Satipo: 2 },
          { Coviriali: 2 },
          { Llaylla: 2 },
          { Mazamari: 2 },
          { "Pampa Hermosa": 2 },
          { Pangoa: 2 },
          { "Rio Negro": 2 },
          { "Rio Tambo": 2 },
        ],
      },
      {
        Tarma: [
          { Acobamba: 2 },
          { Huasahuasi: 2 },
          { Palca: 2 },
          { Palcamayo: 2 },
          { "San Pedro de Cajas": 2 },
          { Tapo: 2 },
          { Tarma: 3 },
          { "La Union": 3 },
          { Huaricolca: 3 },
        ],
      },
      {
        Concepcion: [
          { Concepcion: 3 },
          { Aco: 3 },
          { Chambara: 3 },
          { "Heroinas Toledo": 3 },
          { Manzanares: 3 },
          { Matahuasi: 3 },
          { Mito: 3 },
          { "Nueve de Julio": 3 },
          { Orcotuna: 3 },
          { "San Jose de Quero": 3 },
          { "Santa Rosa de Ocopa": 3 },
          { Andamarca: 2 },
          { Cochas: 2 },
          { Comas: 2 },
          { "Mariscal Castilla": 2 },
        ],
      },
      {
        Chupaca: [
          { Chupaca: 3 },
          { Ahuac: 3 },
          { "Chongos Bajo": 3 },
          { Huachac: 3 },
          { "Huamancaca Chico": 3 },
          { "San Juan de Yscos": 3 },
          { "San Juan de Jarpa": 3 },
          { "Tres de Diciembre": 3 },
          { Yanacancha: 3 },
        ],
      },
      {
        Huancayo: [
          { Parihuanca: 2 },
          { "Santo Domingo de Acobamba": 2 },
          { Carhuacallanga: 3 },
          { Chacapampa: 3 },
          { Chicche: 3 },
          { Chilca: 3 },
          { "Chongos Alto": 3 },
          { Chupuro: 3 },
          { Colca: 3 },
          { Cullhuas: 3 },
          { "El Tambo": 3 },
          { Huacrapuquio: 3 },
          { Hualhuas: 3 },
          { Huancan: 3 },
          { Huancayo: 3 },
          { Huasicancha: 3 },
          { Huayucachi: 3 },
          { Ingenio: 3 },
          { Pilcomayo: 3 },
          { Pucara: 3 },
          { Quichuay: 3 },
          { Quilcas: 3 },
          { "San Agustin": 3 },
          { "San Jeronimo de Tunan": 3 },
          { Saño: 3 },
          { Sapallanga: 3 },
          { Sicaya: 3 },
          { Viques: 3 },
        ],
      },
      {
        Jauja: [
          { Jauja: 3 },
          { Acolla: 3 },
          { Aura: 3 },
          { Canchayllo: 3 },
          { Curicaca: 3 },
          { "El Mantaro": 3 },
          { Huamali: 3 },
          { Huaripampa: 3 },
          { Huertas: 3 },
          { Janjaillo: 3 },
          { Julcan: 3 },
          { "Leonor Ordoñez": 3 },
          { Llocllapampa: 3 },
          { Marco: 3 },
          { Masma: 3 },
          { "Masma Chicche": 3 },
          { Muqui: 3 },
          { Muquiyauyo: 3 },
          { Paca: 3 },
          { Paccha: 3 },
          { Pancan: 3 },
          { Parco: 3 },
          { Pomacancha: 3 },
          { "San Lorenzo": 3 },
          { "San Pedro de Chunan": 3 },
          { Sausa: 3 },
          { Sincos: 3 },
          { "Tunan Marca": 3 },
          { Yauli: 3 },
          { Yauyos: 3 },
          { Apata: 2 },
          { Molinos: 2 },
          { Monobamba: 2 },
          { Ricran: 2 },
        ],
      },
      {
        Junin: [{ Carhuamayo: 2 }, { Ulcumayo: 2 }, { Junin: 3 }, { Ondores: 3 }],
      },
      {
        Yauli: [
          { Chacapalpa: 3 },
          { "Huay-Huay": 3 },
          { "La Oroya": 3 },
          { Marcapomacocha: 3 },
          { Morococha: 3 },
          { Paccha: 3 },
          { "Santa Barbara de Carhuacayan": 3 },
          { "Santa Rosa de Sacco": 3 },
          { Suitucancha: 3 },
          { Yauli: 3 },
        ],
      },
    ],
  },
  {
    LaLibertad: [
      {
        Bolivar: [
          { Bolivar: 2 },
          { Bambamarca: 2 },
          { Condormarca: 2 },
          { Longotea: 2 },
          { Uchumarca: 2 },
          { Ucuncha: 2 },
        ],
      },
      {
        Pataz: [
          { Tayabamba: 2 },
          { Buldibuyo: 2 },
          { Chillia: 2 },
          { Huancaspata: 2 },
          { Huaylillas: 2 },
          { Huayo: 2 },
          { Ongon: 2 },
          { Parcoy: 2 },
          { Pataz: 2 },
          { Pias: 2 },
          { "Santiago de Challas": 2 },
          { Taurija: 2 },
          { Urpay: 2 },
        ],
      },
      {
        "Sanchez Carrion": [
          { Cochorco: 2 },
          { Sartimbamba: 2 },
          { Huamachuco: 3 },
          { Chugay: 3 },
          { Curgos: 3 },
          { Marcabal: 3 },
          { Sanagoran: 3 },
          { Sarin: 3 },
        ],
      },
      {
        "Santiago de Chuco": [
          { "Santiago de Chuco": 3 },
          { Angasmarca: 3 },
          { Cachicadan: 3 },
          { Mollebamba: 3 },
          { Mollepata: 3 },
          { Quiruvilca: 3 },
          { "Santa Cruz de Chuca": 3 },
          { Sitabamba: 3 },
        ],
      },
      {
        "Gran Chimu": [{ Cascas: 3 }, { Lucma: 3 }, { Marmot: 3 }, { Sayapullo: 3 }],
      },
      {
        Julcan: [{ Julcan: 3 }, { Calamarca: 3 }, { Carabamba: 3 }, { Huaso: 3 }],
      },
      {
        Otuzco: [
          { Otuzco: 3 },
          { Agallpampa: 3 },
          { Charat: 3 },
          { Haranchal: 3 },
          { "La Cuesta": 3 },
          { Mache: 3 },
          { Paranday: 3 },
          { Salpo: 3 },
          { Sinsicap: 3 },
          { Usquil: 3 },
        ],
      },
      {
        Chepen: [{ Chepen: 4 }, { Pacanga: 4 }, { "Pueblo Nuevo": 4 }],
      },
      {
        Ascope: [
          { Ascope: 4 },
          { Chicama: 4 },
          { Chocope: 4 },
          { "Magdalena de Cao": 4 },
          { Paijan: 4 },
          { Razuri: 4 },
          { "Santiago de Cao": 4 },
          { "Casa Grande": 4 },
        ],
      },
      {
        Pacasmayo: [
          { "San Pedro de Lloc": 4 },
          { Guadalupe: 4 },
          { Jequetepeque: 4 },
          { Pacasmayo: 4 },
          { "San Jose": 4 },
        ],
      },
      {
        Trujillo: [
          { Trujillo: 4 },
          { "El Porvenir": 4 },
          { "Florencia de Mora": 4 },
          { Huanchaco: 4 },
          { "La Esperanza": 4 },
          { Laredo: 4 },
          { Moche: 4 },
          { Poroto: 4 },
          { Salaverry: 4 },
          { Simbal: 4 },
          { "Victor Larco Herrera": 4 },
        ],
      },
      {
        Viru: [{ Viru: 4 }, { Chao: 4 }, { Guadalupito: 4 }],
      },
    ],
  },
  {
    Lambayeque: [
      {
        Ferreñafe: [
          { Cañaris: 3 },
          { Incahuasi: 3 },
          { Ferreñafe: 4 },
          { "Manuel Antonio Mesones Muro": 4 },
          { Pitipo: 4 },
          { "Pueblo Nuevo": 4 },
        ],
      },
      {
        Lambayeque: [
          { Salas: 3 },
          { Lambayeque: 4 },
          { Chochope: 4 },
          { Illimo: 4 },
          { Jayanca: 4 },
          { Mochumi: 4 },
          { Mochumi: 4 },
          { Morrope: 4 },
          { Motupe: 4 },
          { Olmos: 4 },
          { Pacora: 4 },
          { "San Jose": 4 },
          { Tucume: 4 },
        ],
      },
      {
        Chiclayo: [
          { Chiclayo: 4 },
          { Chongoyape: 4 },
          { Eten: 4 },
          { "Eten Puerto": 4 },
          { "Jose Leonardo Ortiz": 4 },
          { "La Victoria": 4 },
          { Lagunas: 4 },
          { Monsefu: 4 },
          { "Nueva Arica": 4 },
          { Oyotun: 4 },
          { Picsi: 4 },
          { Pimentel: 4 },
          { Reque: 4 },
          { "Santa Rosa": 4 },
          { Saña: 4 },
          { Cayalti: 4 },
          { Patapo: 4 },
          { Pomalca: 4 },
          { Pucala: 4 },
          { Tuman: 4 },
        ],
      },
    ],
  },
  {
    Loreto: [
      {
        "Mariscal Ramon Castilla": [{ "Ramon Castilla": 1 }, { Pebas: 1 }, { "San Pablo": 1 }, { Yavari: 1 }],
      },
      {
        Maynas: [
          { "Alto Nanay": 1 },
          { Belen: 1 },
          { "Fernando Lores": 1 },
          { Indiana: 1 },
          { Iquitos: 1 },
          { "Las Amazonas": 1 },
          { Mazan: 1 },
          { Napo: 1 },
          { Punchana: 1 },
          { Putumayo: 1 },
          { "San Juan Bautista": 1 },
          { "Tnte. Manuel Clavero": 1 },
          { "Torres Causana": 1 },
        ],
      },
      {
        Requena: [
          { Saquena: 1 },
          { Requena: 2 },
          { Capelo: 2 },
          { Soplin: 2 },
          { Tapiche: 2 },
          { "Jenaro Herrera": 2 },
          { Yaquerana: 2 },
          { "Alto Tapiche": 2 },
          { "Emilio San Martin": 2 },
          { Maquia: 2 },
          { Puinahua: 2 },
        ],
      },
      {
        Loreto: [{ Nauta: 2 }, { Parinari: 2 }, { Tigre: 2 }, { Trompeteros: 2 }, { Urarinas: 2 }],
      },
      {
        "Alto Amazonas": [
          { Lagunas: 2 },
          { Yurimaguas: 3 },
          { Balsapuerto: 3 },
          { Jeberos: 3 },
          { "Santa Cruz": 3 },
          { "Tnte. Cesar Lopez Rojas": 3 },
        ],
      },
      {
        Ucayali: [
          { Contamana: 2 },
          { Inahuaya: 2 },
          { "Padre Marquez": 2 },
          { "Pampa Hermosa": 2 },
          { Sarayacu: 2 },
          { "Alfredo Vargas Guerra": 2 },
          { Yanayacu: 2 },
        ],
      },
      {
        "Datem del Marañon": [
          { Manseriche: 2 },
          { Morona: 2 },
          { Pastaza: 2 },
          { Andoas: 2 },
          { Barranca: 3 },
          { Cahuapanas: 3 },
        ],
      },
    ],
  },
  {
    MadreDeDios: [
      {
        Tambopata: [{ Tambopata: 1 }, { Inambari: 1 }, { "Las Piedras": 1 }, { Laberinto: 1 }],
      },
      {
        Manu: [{ Fitzcarrald: 1 }, { Huepetuhe: 1 }, { "Madre de Dios": 1 }, { Manu: 1 }],
      },
      {
        Tahuamanu: [{ Iñapari: 2 }, { Iberia: 2 }, { Tahuamanu: 2 }],
      },
    ],
  },
  {
    Moquegua: [
      {
        "General Sanchez Cerro": [
          { "La Capilla": 4 },
          { Omate: 3 },
          { Chojata: 3 },
          { Coalaque: 3 },
          { Ichuña: 3 },
          { Lloque: 3 },
          { Matalaque: 3 },
          { Puquina: 3 },
          { Quinistaguillas: 3 },
          { Ubinas: 3 },
          { Yunga: 3 },
        ],
      },
      {
        "Mariscal Nieto": [
          { Moquegua: 4 },
          { Carumas: 3 },
          { Cuchumbaya: 3 },
          { Samegua: 3 },
          { "San Cristobal": 3 },
          { Torata: 3 },
        ],
      },
      {
        Ilo: [{ Ilo: 4 }, { "El Algarrobal": 4 }, { Pacocha: 4 }],
      },
    ],
  },
  {
    Pasco: [
      {
        Pasco: [
          { Huachon: 2 },
          { Huariaca: 2 },
          { Ninacaca: 2 },
          { Pallanchacra: 2 },
          { Paucartambo: 2 },
          { "San Francisco de Asis de Yarusyacan": 2 },
          { Ticlacayan: 2 },
          { Yanacancha: 2 },
          { Chaupimarca: 3 },
          { Huayllay: 3 },
          { "Simon Bolivar": 3 },
          { Tinyahuarco: 3 },
          { Vicco: 3 },
        ],
      },
      {
        "Daniel Alcides Carrion": [
          { Yanahuanca: 3 },
          { Chacayan: 3 },
          { Goyllarisquizga: 3 },
          { Paucar: 3 },
          { "San Pedro de Pillao": 3 },
          { "Santa Ana de Tusi": 3 },
          { Tapuc: 3 },
          { Vilcabamba: 3 },
        ],
      },
      {
        Oxapampa: [
          { Oxapampa: 2 },
          { Chontabamba: 2 },
          { Huancabamba: 2 },
          { Palcazu: 2 },
          { Pozuzo: 2 },
          { "Puerto Bermudez": 2 },
          { "Villa Rica": 2 },
        ],
      },
    ],
  },
  {
    Piura: [
      {
        Huancabamba: [
          { Huancabamba: 3 },
          { Canchaque: 3 },
          { "El Carmen de la Frontera": 3 },
          { Huarmaca: 3 },
          { Lalaquiz: 3 },
          { "San Miguel de El Faique": 3 },
          { Sondor: 3 },
          { Sondorillo: 3 },
        ],
      },
      {
        Ayabaca: [
          { Ayabaca: 3 },
          { Jilili: 3 },
          { Lagunas: 3 },
          { Montero: 3 },
          { Pacaipampa: 3 },
          { Sicchez: 3 },
          { Frias: 4 },
          { Paimas: 4 },
          { Sapillica: 4 },
          { Suyo: 4 },
        ],
      },
      {
        Morropon: [
          { "Buenos Aires": 3 },
          { Chalaco: 3 },
          { Salitral: 3 },
          { "San Juan de Bigote": 3 },
          { "Santa Catalina de Mossa": 3 },
          { Yamango: 3 },
          { Chulucanas: 4 },
          { "La Matanza": 4 },
          { Morropon: 4 },
          { "Santo Domingo": 4 },
        ],
      },
      {
        Piura: [
          { Piura: 4 },
          { Castilla: 4 },
          { Catacaos: 4 },
          { "Cura Mori": 4 },
          { "El Tallan": 4 },
          { "La Arena": 4 },
          { "La Union": 4 },
          { "Las Lomas": 4 },
          { "Tambo Grande": 4 },
        ],
      },
      {
        Paita: [
          { Paita: 4 },
          { Amotape: 4 },
          { Arenal: 4 },
          { Colan: 4 },
          { "La Huaca": 4 },
          { Tamarindo: 4 },
          { Vichayal: 4 },
        ],
      },
      {
        Sechura: [
          { Sechura: 4 },
          { "Bellavista de la Union": 4 },
          { Bernal: 4 },
          { "Cristo Nos Valga": 4 },
          { Vice: 4 },
          { "Rinconada Llicuar": 4 },
        ],
      },
      {
        Sullana: [
          { Sullana: 4 },
          { Bellavista: 4 },
          { "Ignacio Escudero": 4 },
          { Lancones: 4 },
          { Marcavelica: 4 },
          { "Miguel Checa": 4 },
          { Querecotillo: 4 },
          { Salitral: 4 },
        ],
      },
      {
        Talara: [
          { Pariñas: 4 },
          { "El Alto": 4 },
          { "La Brea": 4 },
          { Lobitos: 4 },
          { "Los Organos": 4 },
          { Mancora: 4 },
        ],
      },
    ],
  },
  {
    Puno: [
      {
        Sandia: [
          { "Alto Inambari": 1 },
          { "San Juan del Oro": 1 },
          { Yanahuaya: 1 },
          { Cuyocuyo: 2 },
          { Limbani: 2 },
          { Patambuco: 2 },
          { Phara: 2 },
          { Quiaca: 2 },
          { "San Pedro de Putina Punco": 2 },
          { Sandia: 2 },
        ],
      },
      {
        "San Antonio de Putina": [
          { Ananea: 2 },
          { Quilcapuncu: 2 },
          { Sina: 2 },
          { "Pedro Vilca Apaza": 2 },
          { Putina: 2 },
        ],
      },
      {
        Carabaya: [
          { Ayapata: 2 },
          { Coasa: 2 },
          { Crucero: 2 },
          { Ituata: 2 },
          { "San Gaban": 2 },
          { Uscayos: 2 },
          { Ajoyani: 2 },
          { Corani: 2 },
          { Macusani: 2 },
          { Ollachea: 2 },
        ],
      },
      {
        Huancane: [
          { Cojata: 2 },
          { Huancane: 2 },
          { Huatasani: 2 },
          { Inchupalla: 2 },
          { Pusi: 2 },
          { Rosaspata: 2 },
          { Taraco: 2 },
          { "Vilque Chico": 2 },
        ],
      },
      {
        Moho: [{ Huayrapata: 2 }, { Moho: 2 }, { Conima: 2 }, { Tilali: 2 }],
      },
      {
        Puno: [
          { Coata: 2 },
          { Capachica: 2 },
          { Amantani: 2 },
          { Acora: 3 },
          { Atuncolla: 3 },
          { Chucuito: 3 },
          { Huata: 3 },
          { Mañazo: 3 },
          { Paucarcolla: 3 },
          { Pichacani: 3 },
          { Plateria: 3 },
          { Puno: 3 },
          { "San Antonio": 3 },
          { Tiquillaca: 3 },
          { Vilque: 3 },
        ],
      },
      {
        Azangaro: [
          { Azangaro: 2 },
          { Achaya: 2 },
          { Arapa: 2 },
          { Asillo: 2 },
          { Caminaca: 2 },
          { Chupa: 2 },
          { "Jose Domingo Choquehuanca": 2 },
          { Muñani: 2 },
          { Potoni: 2 },
          { Saman: 2 },
          { "San Anton": 2 },
          { "San Jose": 2 },
          { "San Juan de Salinas": 2 },
          { "Santiago de Pupuja": 2 },
          { Tirapata: 2 },
        ],
      },
      {
        Chucuito: [
          { Desaguadero: 3 },
          { Huacullani: 3 },
          { Juli: 3 },
          { Kelluyo: 3 },
          { Pisacoma: 3 },
          { Pomata: 3 },
          { Zepita: 3 },
        ],
      },
      {
        "El Collao": [{ Capazo: 3 }, { Conduriri: 3 }, { Ilave: 3 }, { Pilcuyo: 3 }, { "Santa Rosa": 3 }],
      },
      {
        Lampa: [
          { Calapuja: 2 },
          { Nicasio: 2 },
          { Pucara: 2 },
          { Cabanilla: 3 },
          { Lampa: 3 },
          { Ocuviri: 3 },
          { Palca: 3 },
          { Paratia: 3 },
          { "Santa Lucia": 3 },
          { Vilavila: 3 },
        ],
      },
      {
        Melgar: [
          { Antauta: 2 },
          { Ayaviri: 2 },
          { Cupi: 2 },
          { Llalli: 2 },
          { Macari: 2 },
          { Nuñoa: 2 },
          { Orurillo: 2 },
          { "Santa Rosa": 2 },
          { Umachiri: 2 },
        ],
      },
      {
        "San Roman": [{ Juliaca: 3 }, { Cabana: 3 }, { Cabanillas: 3 }, { Caracoto: 3 }],
      },
      {
        Yunguyo: [
          { Yunguyo: 3 },
          { Anapia: 3 },
          { Copani: 3 },
          { Cuturapi: 3 },
          { Ollaraya: 3 },
          { Tinicachi: 3 },
          { Unicachi: 3 },
        ],
      },
    ],
  },
  {
    SanMartin: [
      {
        Bellavista: [
          { Bellavista: 2 },
          { "Alto Biavo": 2 },
          { "Bajo Biavo": 2 },
          { Huallaga: 2 },
          { "San Pablo": 2 },
          { "San Rafael": 2 },
        ],
      },
      {
        Huallaga: [
          { Saposoa: 2 },
          { "Alto Saposoa": 2 },
          { "El Eslabon": 2 },
          { Piscoyacu: 2 },
          { Sacanche: 2 },
          { "Tingo de Saposoa": 2 },
        ],
      },
      {
        Lamas: [
          { Lamas: 3 },
          { "Alonso de Alvarado": 3 },
          { Barranquita: 3 },
          { Caynarachi: 3 },
          { Cuñumbuqui: 3 },
          { "Pinto Recodo": 3 },
          { Rumisapa: 3 },
          { "San Roque de Cumbaza": 3 },
          { Shanao: 3 },
          { Tabalosos: 3 },
          { Zapatero: 3 },
        ],
      },
      {
        "Mariscal Caceres": [{ Juanjui: 2 }, { Campanilla: 2 }, { Huicungo: 2 }, { Pachiza: 2 }, { Pajarillo: 2 }],
      },
      {
        Picota: [
          { Picota: 2 },
          { "Buenos Aires": 2 },
          { Caspisapa: 2 },
          { Pilluana: 2 },
          { Pucacaca: 2 },
          { "San Cristobal": 2 },
          { "San Hilarion": 2 },
          { Shamboyacu: 2 },
          { "Tingo de Ponasa": 2 },
          { "Tres Unidos": 2 },
        ],
      },
      {
        Moyobamba: [{ Moyobamba: 3 }, { Calzada: 3 }, { Habana: 3 }, { Jepelacio: 3 }, { Soritor: 3 }, { Yantalo: 3 }],
      },
      {
        Rioja: [
          { Rioja: 3 },
          { Awajun: 3 },
          { "Elías Soplin Vargas": 3 },
          { "Nueva Cajamarca": 3 },
          { "Pardo Miguel": 3 },
          { Posic: 3 },
          { "San Fernando": 3 },
          { Yorongos: 3 },
          { "Yurac Yacu": 3 },
        ],
      },
      {
        "San Martin": [
          { Tarapoto: 2 },
          { "Alberto Leveau": 2 },
          { Cacatachi: 2 },
          { Chazuta: 2 },
          { Chipurana: 3 },
          { "El Porvenir": 3 },
          { Huimbayoc: 3 },
          { "Juan Guerra": 3 },
          { "La Banda de Shilcayo": 3 },
          { Morales: 3 },
          { Papapleya: 3 },
          { "San Antonio": 3 },
          { Sauce: 3 },
          { Shapaja: 3 },
        ],
      },
      {
        Tocache: [{ Tocache: 2 }, { "Nuevo Progreso": 2 }, { Polvora: 2 }, { Shunte: 2 }, { Uchiza: 2 }],
      },
      {
        "El Dorado": [
          { "San Jose de Sisa": 3 },
          { "Agua Blanca": 3 },
          { "San Martin": 3 },
          { "Santa Rosa": 3 },
          { Shatoja: 3 },
        ],
      },
    ],
  },
  {
    Tacna: [
      {
        Tarata: [
          { Tarata: 3 },
          { "Heroes Albarracin": 3 },
          { Estique: 3 },
          { "Estique Pampa": 3 },
          { Sitajara: 3 },
          { Susapaya: 3 },
          { Tarucachi: 3 },
          { Ticaco: 3 },
        ],
      },
      {
        Candarave: [
          { Candarave: 3 },
          { Cairani: 3 },
          { Camilaca: 3 },
          { Curibaya: 3 },
          { Huanuara: 3 },
          { Quilahuani: 3 },
        ],
      },
      {
        "Jorge Basadre": [{ Locumba: 4 }, { Ilabaya: 4 }, { Ite: 4 }],
      },
      {
        Tacna: [
          { Palca: 3 },
          { Tacna: 4 },
          { "Alto de la Alianza": 4 },
          { Calana: 4 },
          { "Ciudad Nueva": 4 },
          { Inclan: 4 },
          { Pachia: 4 },
          { Pocollay: 4 },
          { Sama: 4 },
          { "Coronel Gregorio Albarracin Lanchipa": 4 },
        ],
      },
    ],
  },
  {
    Tumbes: [
      {
        "Contralmirante Villar": [{ Zorritos: 4 }, { Casitas: 4 }, { "Canoas de Punta Sal": 4 }],
      },
      {
        Tumbes: [
          { Tumbes: 4 },
          { Corrales: 4 },
          { "La Cruz": 4 },
          { "Pampas de Hospital": 4 },
          { "San Jacinto": 4 },
          { "San Juan de la Virgen": 4 },
        ],
      },
      {
        Zarumilla: [{ Zarumilla: 4 }, { "Aguas Verdes": 4 }, { Matapalo: 4 }, { Papayal: 4 }],
      },
    ],
  },
  {
    Ucayali: [
      {
        Purus: [{ Purus: 1 }],
      },
      {
        Atalaya: [{ Raimondi: 2 }, { Sepahua: 2 }, { Tahuania: 2 }, { Yurua: 2 }],
      },
      {
        "Padre Abad": [{ Curimana: 2 }, { Irazola: 2 }, { "Padre Abad": 2 }],
      },
      {
        "Coronel Portillo": [
          { Calleria: 2 },
          { Campoverde: 2 },
          { Iparia: 2 },
          { Manantay: 2 },
          { Masisea: 2 },
          { "Nueva Requena": 2 },
          { Yarinacocha: 2 },
        ],
      },
    ],
  },
];

export function cargarDep(select, opciones) {
  opciones.map((dep, i) => {
    var option = document.createElement("option");
    option.text = Object.keys(dep)[0];
    option.value = i;
    select.add(option);
  });
}
export function cargarPro(select, provincias) {
  select.innerHTML = "";
  provincias.map((dep, i) => {
    var option = document.createElement("option");
    option.text = Object.keys(dep)[0];
    option.value = i;
    select.add(option);
  });
}
export function cargarDis(select, opciones) {
  select.innerHTML = "";
  opciones.map((dep, i) => {
    var option = document.createElement("option");
    option.text = Object.keys(dep)[0];
    option.value = i;
    select.add(option);
  });
}

export const categoriasEdificacion = [
  {
    id: 1,
    categoria: "A1_Escenciales",
    factor_U: 1.5,
    text: "Edificaciones del sector salud (públicos y privados) del segundo y tercer nivel, según lo normado por el ministerio de Salud.",
    tipos: ["Con Aisladores sísmicos zonas (4,3,2,1)", "Sin aísladores sísmicos - Zonas (2,1)"],
  },
  {
    id: 2,
    categoria: "A2_Escenciales",
    factor_U: 1.5,
    text: "Edificaciones esenciales cuya función no debería interrumpirse inmediatamente despues de que ocurra un sismo severo. Edificaciones que pueden servir de refugio después de un desastre. Se incluyen edificaciones cuyo colapso puede presentar un riesgo adicional.",
    tipos: [
      "Clínicas",
      "Hospitales",
      "Postas médicas",
      "Puertos",
      "Aeropuertos",
      "Estaciones ferroviarias de pasajeros",
      "Sistemas masivos de transporte",
      "Centrales de comunicaciones",
      "Locales municipales",
      "Estaciones de bomberos",
      "Cuarteles de las fuerzas armadas y policías",
      "Inst. generación, transfor. Electricidad",
      "Reservorios de agua",
      "Plantas de tratamiento de agua",
      "Instituciones educativas nivel inicial",
      "Instituciones educativas nivel primaria",
      "Instituciones educativas nivel secundaria",
      "Institutos superiores tecnológicos",
      "Universidades",
      "Grandes hornos ",
      "Fábricas",
      "Depósitos materiales inflamables, tóxicos",
      "Almacén información esencial del estado",
      "A2-Otros",
    ],
  },
  {
    id: 3,
    categoria: "B_Importantes",
    factor_U: 1.3,
    text: "Edificaciones donde se reúnen gran cantidad de personas. Se incluyen las edificaciones que guardan patrimonios valiosos.",
    tipos: [
      "Cines",
      "Teatros",
      "Estadios",
      "Coliseos",
      "Centros comerciales",
      "Terminales de buses de pasajeros",
      "Establecimientos penitenciarios",
      "Museos",
      "Bibliotecas",
      "Depósitos de granos",
      "Almacenes importanes de abastecimiento",
      "B - Otros",
    ],
  },
  {
    id: 4,
    categoria: "C_Comunes",
    factor_U: 1,
    text: "Edificaciones comunes cuya falla no acarree peligros adicionales de incendios o fugas de contaminantes.",
    tipos: ["Viviendas", "Oficinas", "Hoteles", "Restaurantes", "Instalaciones Industriales", "Depósitos", "C - Otros"],
  },
  {
    id: 5,
    categoria: "D_temporales",
    factor_U: 0.5,
    text: "Edificaciones temporales.",
    tipos: ["Construcciones provisionales", "Depósitos temporales", "Casetas", "construcciones similares", "D - Otros"],
  },
];

export function cargarCategorias(select) {
  /*   select.innerHTML = ''; */

  for (const categoria of categoriasEdificacion) {
    console.log(categoriasEdificacion);
    var option = document.createElement("option");
    option.text = categoria.categoria;
    option.value = categoria.id;
    select.add(option);
    /* for (const tipo of categoria.tipos) {
      const option = document.createElement('option');
      option.text = tipo;
      option.value = tipo;
      optionGrupo.appendChild(option);
    } */
  }
}

export function cargarTipo(select, Id, result, text) {
  categoriasEdificacion.map((cat) => {
    if (cat.id == Id) {
      result.innerText = cat.factor_U;
      text.innerText = cat.text;
      cat["tipos"].map((tipo) => {
        var option = document.createElement("option");
        option.text = tipo;
        option.value = tipo;
        select.add(option);
      });
    }
  });
}
